id: 789ad61d49a54396a830946750880eed
initial_creation_type: ocr
source_metadata:
  volumes:
    d9b3c68c730d41c4b904a225cba7be0b:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: རང་བཞིན་གསུམ་ངེས་པར་བསྟན་པ།
      total_pages: 1517
      volume_number: 77
